# Generated by Django 5.2.13 on 2026-04-22 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semireboque',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_semireboque', models.CharField(max_length=255)),
                ('eixos_semireboque', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_veiculo', models.CharField(max_length=255, verbose_name='Tipo de veiculo')),
                ('eixos_veiculo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitantes', to='novacotacao.cliente')),
            ],
        ),
    ]
