# Generated by Django 5.2.13 on 2026-04-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacotacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semireboque',
            name='eixos_semireboque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='telefone',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='eixos_veiculo',
            field=models.IntegerField(),
        ),
    ]
