# Generated by Django 5.2.13 on 2026-04-22 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacotacao', '0002_alter_cliente_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcmsEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=2)),
                ('destino', models.CharField(max_length=2)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'tabela_icms',
                'ordering': ['origem', 'destino'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustoDespesaOperacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('MOEDA', 'Valor Fixo (R$)')], max_length=15)),
            ],
            options={
                'verbose_name': 'Custo/Despesa Operacional',
                'verbose_name_plural': 'Custos/Despesas Operacionais',
            },
        ),
        migrations.CreateModel(
            name='CustoGris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MOTORISTA', 'Pesquisa Motorista'), ('VEICULO', 'Pesquisa Veículos/Carreta'), ('CONJUNTO', 'Conjunto: Motorista e Veículo'), ('GERAL', 'GRIS Geral')], max_length=20)),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Custo GRIS',
                'verbose_name_plural': 'Custos GRIS',
            },
        ),
        migrations.CreateModel(
            name='CustoSeguroCarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
                ('taxa', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                'verbose_name': 'Custo Seguro Carga',
                'verbose_name_plural': 'Custos Seguro Carga',
            },
        ),
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Imposto',
                'verbose_name_plural': 'Impostos',
            },
        ),
        migrations.CreateModel(
            name='TabelaPrecoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cliente')),
                ('seguro_taxa_1', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='% Seguro (1)')),
                ('seguro_taxa_2', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='% Seguro (2)')),
                ('valor_mercadoria_limite', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Vlr. Mercadoria Limite')),
                ('valor_ajudante', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Ajudante (R$)')),
                ('taxa_utilitarios', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Utilitários')),
                ('taxa_3_4', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa 3/4')),
                ('taxa_toco', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Toco')),
                ('taxa_truck', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Truck')),
                ('taxa_cavalo_4x2', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Cavalo 4x2')),
                ('taxa_cavalo_6x2', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Cavalo 6x2')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_cliente'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMarkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calculo', models.DateTimeField(auto_now_add=True)),
                ('valor_custo_operacional', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Custo (R$)')),
                ('percentual_lucro', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Lucro Base (%)')),
                ('percentual_financeiro', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Financeiro (%)')),
                ('percentual_pamcard', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pamcard (%)')),
                ('prazo_dias', models.IntegerField(verbose_name='Prazo de Pagamento (Dias)')),
                ('percentual_encargo_prazo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Encargo Prazo (%)')),
                ('valor_final_frete', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Final Gerado (R$)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novacotacao.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Registro de Markup',
                'verbose_name_plural': 'Registros de Markup',
                'ordering': ['-data_calculo'],
            },
        ),
    ]
