# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novacotacao", "0006_alter_cotacao_decimal_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="taxa_correcao",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Taxa de correção (R$)",
            ),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="ctrb_somar_taxa_correcao",
            field=models.BooleanField(
                default=False,
                verbose_name="Somar taxa de correção no CTRB orçado",
            ),
        ),
    ]
