# Generated by Django 5.2.13 on 2026-04-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTaxasConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, unique=True)),
                ('seguro_taxa_1', models.DecimalField(decimal_places=5, max_digits=8)),
                ('seguro_taxa_2', models.DecimalField(decimal_places=5, max_digits=8)),
                ('valor_mercadoria_limite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_ajudante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_utilitarios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxa_cavalo_4x2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxa_truck', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxa_toco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxa_3_4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxa_cavalo_6x2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'cliente_taxas_config',
                'ordering': ['nome_cliente'],
            },
        ),
        migrations.DeleteModel(
            name='TabelaCustCliente',
        ),
    ]
