# Generated by Django 5.2.13 on 2026-04-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0002_clientetaxasconfig_delete_tabelacustcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupClienteFaixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('faixa', models.PositiveSmallIntegerField(help_text='Nível/faixa (ex: 1..n)')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de markup (ex: 20.00)', max_digits=6)),
            ],
            options={
                'verbose_name': 'Configuração de Markup',
                'verbose_name_plural': 'Configurações de Markup',
                'ordering': ['nome_cliente', 'faixa'],
                'constraints': [models.UniqueConstraint(fields=('nome_cliente', 'faixa'), name='uniq_markup_cliente_faixa')],
            },
        ),
    ]
