# Generated by Django 5.2.13 on 2026-04-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0003_markupclientefaixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markupclientefaixa',
            name='percentual',
        ),
        migrations.AddField(
            model_name='markupclientefaixa',
            name='percentual_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base (%) usada no divisor do CTRB (ex: 59.23)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='markupclientefaixa',
            name='percentual_markup',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Markup/Percentual (%) (ex: 20.00)', max_digits=6, null=True),
        ),
    ]
