# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0005_imposto_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizISS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alíquota (%)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matriz ISS',
                'verbose_name_plural': 'Matrizes ISS',
                'ordering': ['cidade'],
            },
        ),
        migrations.AddConstraint(
            model_name='matriziss',
            constraint=models.UniqueConstraint(fields=('cidade',), name='unique_iss_cidade'),
        ),
    ]
