# Generated by Django 5.2.14 on 2026-05-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0014_remove_qualp_models_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imposto',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Imposto', 'verbose_name_plural': 'Impostos'},
        ),
        migrations.AlterModelOptions(
            name='markupclientefaixa',
            options={'ordering': ['nome_cliente', 'percentual_markup'], 'verbose_name': 'Configuração de Markup', 'verbose_name_plural': 'Configurações de Markup'},
        ),
        migrations.AlterField(
            model_name='markupclientefaixa',
            name='percentual_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual base (%) aplicado no CTRB (ex: 59.23).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='markupclientefaixa',
            name='percentual_markup',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual LAIR (%) (ex: 20.00).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='matriziss',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
