# Generated by Django 5.2.14 on 2026-05-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0017_remove_markup_lair_zero_um'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'novacotacao_cliente',
                'ordering': ['nome_empresa'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField()),
            ],
            options={
                'db_table': 'novacotacao_solicitante',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
    ]
